# fly.toml app configuration file generated for 65villa-com on 2024-03-30T07:56:56+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '65villa-com'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
