name: Deployment
on:
  workflow_dispatch:
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_PROD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy api
        run: flyctl deploy
